
import { Header } from "@/components/Header";
import { OutfitCard } from "@/components/OutfitCard";
import { useApp } from "@/context/AppContext";
import { Button } from "@/components/ui/button";
import { Heart } from "lucide-react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";

const Outfits = () => {
  const { outfits } = useApp();
  const [showFavoritesOnly, setShowFavoritesOnly] = useState(false);
  const navigate = useNavigate();
  
  const displayedOutfits = showFavoritesOnly
    ? outfits.filter(outfit => outfit.favorite)
    : outfits;
  
  return (
    <div className="min-h-screen bg-gradient-to-b from-white to-fashion-cream">
      <Header />
      
      <main className="container mx-auto py-8 px-4">
        <div className="max-w-7xl mx-auto space-y-8">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <h1 className="text-3xl font-bold text-fashion-primary mb-2">My Outfits</h1>
              <p className="text-fashion-darktext">
                View all your outfit recommendations generated by Gemini AI
              </p>
            </div>
            
            <div className="flex flex-col sm:flex-row gap-3">
              <Button
                variant="outline"
                onClick={() => setShowFavoritesOnly(!showFavoritesOnly)}
                className={`flex items-center gap-2 ${
                  showFavoritesOnly 
                    ? "bg-fashion-secondary text-white border-fashion-secondary" 
                    : "border-fashion-primary text-fashion-primary"
                }`}
              >
                <Heart className={showFavoritesOnly ? "fill-white" : ""} size={16} />
                {showFavoritesOnly ? "Show All Outfits" : "Show Favorites Only"}
              </Button>
              
              <Button
                onClick={() => navigate("/")}
                className="bg-fashion-primary hover:bg-fashion-primary/90"
              >
                Get New Recommendations
              </Button>
            </div>
          </div>
          
          {displayedOutfits.length > 0 ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {displayedOutfits.map(outfit => (
                <OutfitCard key={outfit.id} outfit={outfit} />
              ))}
            </div>
          ) : (
            <div className="p-12 text-center border rounded-lg bg-fashion-cream">
              {showFavoritesOnly ? (
                <div className="space-y-4">
                  <p className="text-fashion-primary text-lg">You don't have any favorite outfits yet.</p>
                  <Button 
                    onClick={() => setShowFavoritesOnly(false)}
                    variant="outline"
                    className="border-fashion-primary text-fashion-primary hover:bg-fashion-primary hover:text-white"
                  >
                    View All Outfits
                  </Button>
                </div>
              ) : (
                <div className="space-y-4">
                  <p className="text-fashion-primary text-lg">No outfits found. Generate your first AI recommendation!</p>
                  <Button 
                    onClick={() => navigate("/")}
                    className="bg-fashion-primary hover:bg-fashion-primary/90"
                  >
                    Get AI Recommendations
                  </Button>
                </div>
              )}
            </div>
          )}
        </div>
      </main>
      
      <footer className="mt-auto py-6 bg-fashion-primary text-white">
        <div className="container mx-auto px-4 text-center">
          <p>Style Seeker - Powered by Gemini AI</p>
        </div>
      </footer>
    </div>
  );
};

export default Outfits;
